Use player config builder
bitmovin/bitmovin-player-webos-demo pull request #18
Opened 2024-09-30 15:30 UTC by offnertho

This PR adds the usage of the newly introduced [PlayerConfigBuilder](https://cdn.bitmovin.com/player/web/8/docs/classes/Util.PlayerConfigBuilder.html)

This will help simplifying the setup of TV applications.

2024-09-30 15:46 UTC, dweinber commented on src/js/main.js
> +  };
Can be removed as this is not a valid config anymore in v8: https://cdn.bitmovin.com/player/web/8/docs/interfaces/Core.StyleConfig.html

```suggestion
```

2024-09-30 15:46 UTC, dweinber commented on src/js/main.js
>    };
Maybe it would be better to just do that in the [SourceConfig](https://cdn.bitmovin.com/player/web/8/docs/interfaces/Core.SourceConfig.html#analytics)? They're anyway per-source. We could add [customUserId](https://cdn.bitmovin.com/player/web/8/docs/interfaces/Analytics.AnalyticsConfig.html#customUserId) here to show how to do it.

Wouldn't the following work too? It avoids the `...` operator which older TVs don't support natively without transpiling the code

```suggestion
conf.analytics.customUserId = 'my-custom-user-id';
```

2024-10-01 08:52 UTC, dweinber requested changes

2024-10-01 08:52 UTC, dweinber commented on src/js/main.js
> +    ...conf.analytics,
Please don't use the spread operator. This example is meant to be ready-to-use, and older TVs might not support this and will throw a syntax error.

2024-10-01 09:31 UTC, offnertho commented on src/js/main.js
> +    ...conf.analytics,
👍

2024-10-01 09:56 UTC, dweinber approved these changes
Nice improvement! 💪

2024-10-01 10:06 UTC, merged